language: ruby
addons:
  apt:
    packages:
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - lmodern
    - rubber
script:
- bash rubber.sh
deploy:
  provider: releases
  api_key:
    secure: b6OKfHsAT7I0+t+g5iMAwcQz82a3Jlw7fenrn1NG/ZrYkfOE5W49AMJiTxhmuBBuzSEbNVB0ASxN1rLyxrkO9/pjn1AvRiE74ykO3zCKNvliZxP2YZZtAgKwaBqssf2hrn0weAAXQP/DrI+f9LCEiniRGoHTqA5VOi3w0vg14EEkeU23WoVUy2YDb4Ng3r0mTVp0RXbbVxUcfsFJrHksabpeaAIrlK2idR6Zw8PlrJxel8IyRqjLFCMURaGZm+YHxULBtJeLryp3mzNrfwfhtXzLZnAQE+dsocTPtDSvtX2kWEvfctZorRIBx8Vyhm0uKgR+ypFYtj8R7pVf8brPnIQ1aSOhBDTB8bvQKpoCvTocx5QlxFobTFgTBJwLe+gMtvESzUsmtYwHXqdRECC4XIdEjE8RPc2WnzmtuTX7waOKE9WkwyNuGL2RHuAwaHqrDKfW3mJ7aM2ul1VX13iNFU98FX0I65PyY6vPOJ0ynQVO+UHTy45tpIYQ7825ZJkWHy8GKKDy25ZlZExN5D2YAMAA78lOr8+GNTwbraLcgiqDFkUpsaG0FvKGsAgmfQIM28If+AsPM7OkweZngPkW2NnGTEhmqyzAtRB1kCobIkppXI2i9oK/Fr0ISxIwAaWKrQU6DOgQI+1QtrndIU8U3nS8byDk40kC04dWym6J+Bk=
  file: CV.pdf
  on:
    repo: mafagafogigante/cv
