addons:
  apt:
    packages:
    - biber
    - ghostscript
    - latex-xcolor
    - lmodern
    - rubber
    - texlive-bibtex-extra
    - texlive-extra-utils
    - texlive-fonts-extra
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-math-extra

script:
- bash rubber.sh

deploy:
  provider: releases
  api_key:
    secure: df4YJaK0xFB/oCmNZYq6kQ+J/gSC33e4BpEEO41o023mstA5oHrQ6XxjEKSxca/+7WIZSsE6EzsmhJ6vait6yclIn+IDZg9nHvZ4yzmIpW9+cs0YQVCJNIrkUoCH4URCbtVTJ/HbhDHsGKZb9clRyHICE/hnymfJBtXHB3hyUSJzLzLQVCKKudis2BPQ1H/ylfMR3m6YKVjUhWhA2G98K6wyt0RKIUdYxp3VWNyji505EJjV0ocT9zWI46FF3zywmMRQm2wZ6JZ7SyD1Dy3trq7spHAoFLKjb9gWGkKQAsrMbisHjJRrEbvNBRIpYuKtqzij33dL45J6DF/W7LEJsjlhEKpPRAKDfninPgBkFT1UcbM/HTDfPYhEINs6rhi4UAgUrAaVKHV4Jb8KvfdQnf8hUifmEuvsSwMvXTdDYd7Z1t1YdIAYFtoZMzyhEwRRm4nWky48GtI/Rfsb/+wB6NJFsDjjW+cG2R2bGobbrL2lmmaU6s1ragSMk+q6hWi9xFXmbeaw177QObmOKrFlzCIocvH+FhrU3PtQYFePJqMroyPAfz11aDbwvBFr/Fpe3Hcp5PEmimlLyCmFGpUNMYAQ0q7aasg3thJty90JzCYw4P4e84AopSBfY51iP0G3HYIusTwDb3ObJoH3C5K5N4S+ecPlTgJFx/uzsByVRDk=
  file: CV.pdf
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: bernardosulzbach/cv
