# Ubuntu 20.04
dist: focal

addons:
  apt:
    packages:
    - biber
    - ghostscript
    - lmodern
    - rubber
    - texlive-bibtex-extra
    - texlive-extra-utils
    - texlive-fonts-extra
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-science

script:
- bash rubber.sh

deploy:
  provider: releases
  api_key:
    secure: vku9xRe0aGsqXKtkumvm6QsZHXwtkXFnoYezZfS27UFZsWppUl66rOzg3hEdjRhk74P3KwFPzplaKu0kPHeFCXu9Jvu832SiEYHzUA+k6hriFPQPp1yWTignHnv3oug4AHqoql3WKMayrhL0YmhXIQvU4GdxXB0TbWk72dUoGaumdw+bVKy9zZ5GM6nKMyA1YQlA1Rb/nXRUzoXoRE2KzvODxV5bLz4IBqK0ARFd+8hZ/oxKLw6t7dds1bxfYID7zFjzmqbusKAaaa14stzXXaLdhwak7Q75fvd7diaeOIAn//SQvytoLwH0lcQDbafRYTwxUX9Hf1qmZVMHQfC9f5Q+BjqdPEcmV7Ju6jc1M7LXFtbAdFkaGxRxpQK43tRiDq62i9fUqFmz5biDtPs9RAkwdDk1L0sMqYrnuiZgk8UHAD9xPDeGss9Hpyoe0lcwlKUsOqeMCnB7GP2+VPjSC47mjdp750rHvYvXnn5SyxpRCG4MdmPtxjLOj9Nm5o6RWHH3WVY2xyMM+gOMJYE2/5FfZ8wlRTH239xAm3ARUdpd+90l9WF78VuZfsCP7inU1ECdgVylTnfH2vl5t6K3zfCohX8y1qIH1eNxXR6ZJbhmmyGzi1X8FnkVuO0YWrTwOJ0M7T/Aix6tz7zS6WFgxa2TjCER83ojY9+Ghw76ujg=
  file: CV.pdf
  skip_cleanup: 'true'
  on:
    tags: true
    all_branches: true
    repo: bernardosulzbach/cv
